-- MySQL Script generated by MySQL Workbench
-- Mon Nov  1 14:22:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vuelos_semillero
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vuelos_semillero
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vuelos_semillero` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `vuelos_semillero` ;

-- -----------------------------------------------------
-- Table `vuelos_semillero`.`aerolinea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos_semillero`.`aerolinea` (
  `idaerolinea` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idaerolinea`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vuelos_semillero`.`aeropuerto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos_semillero`.`aeropuerto` (
  `idaeropuerto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idaeropuerto`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vuelos_semillero`.`aeropuerto-aerolinea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos_semillero`.`aeropuerto-aerolinea` (
  `idaeropuerto-aerolinea` INT NOT NULL AUTO_INCREMENT,
  `idAerolinea` INT NOT NULL,
  `idAeropuerto` INT NOT NULL,
  PRIMARY KEY (`idaeropuerto-aerolinea`),
  INDEX `fk_aeropuerto-aerolinea_aerolinea_id_idx` (`idAerolinea` ASC) VISIBLE,
  INDEX `fk_aeropuerto-aerolinea_aeropuerto_id_idx` (`idAeropuerto` ASC) VISIBLE,
  CONSTRAINT `fk_aeropuerto-aerolinea_aerolinea_id`
    FOREIGN KEY (`idAerolinea`)
    REFERENCES `vuelos_semillero`.`aerolinea` (`idaerolinea`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aeropuerto-aerolinea_aeropuerto_id`
    FOREIGN KEY (`idAeropuerto`)
    REFERENCES `vuelos_semillero`.`aeropuerto` (`idaeropuerto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 68
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vuelos_semillero`.`avion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos_semillero`.`avion` (
  `idavion` INT NOT NULL AUTO_INCREMENT,
  `capacidad` INT NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idavion`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vuelos_semillero`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos_semillero`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 1093642434
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vuelos_semillero`.`vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos_semillero`.`vuelo` (
  `idvuelo` INT NOT NULL AUTO_INCREMENT,
  `numeroVuelo` VARCHAR(45) NOT NULL,
  `idAerolinea` INT NOT NULL,
  `idAvion` INT NOT NULL,
  PRIMARY KEY (`idvuelo`),
  INDEX `fk_vuelo_aerolinea_id_idx` (`idAerolinea` ASC) VISIBLE,
  INDEX `fk_vuelo_avion_id_idx` (`idAvion` ASC) VISIBLE,
  CONSTRAINT `fk_vuelo_aerolinea_id`
    FOREIGN KEY (`idAerolinea`)
    REFERENCES `vuelos_semillero`.`aerolinea` (`idaerolinea`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_vuelo_avion_id`
    FOREIGN KEY (`idAvion`)
    REFERENCES `vuelos_semillero`.`avion` (`idavion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vuelos_semillero`.`pasaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos_semillero`.`pasaje` (
  `idpasaje` INT NOT NULL AUTO_INCREMENT,
  `clase` VARCHAR(45) NOT NULL,
  `silla` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(20,0) NOT NULL,
  `fechaCompra` VARCHAR(45) NOT NULL,
  `horaCompra` VARCHAR(45) NOT NULL,
  `idCliente` INT NOT NULL,
  `idVuelo` INT NOT NULL,
  PRIMARY KEY (`idpasaje`),
  INDEX `fk_pasaje_cliente_id_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_pasaje_vuelo_id_idx` (`idVuelo` ASC) VISIBLE,
  CONSTRAINT `fk_pasaje_cliente_id`
    FOREIGN KEY (`idCliente`)
    REFERENCES `vuelos_semillero`.`cliente` (`idcliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pasaje_vuelo_id`
    FOREIGN KEY (`idVuelo`)
    REFERENCES `vuelos_semillero`.`vuelo` (`idvuelo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vuelos_semillero`.`ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos_semillero`.`ruta` (
  `idruta` INT NOT NULL AUTO_INCREMENT,
  `ciudadOrigen` VARCHAR(45) NOT NULL,
  `ciudadDestino` VARCHAR(45) NOT NULL,
  `fechaVuelo` DATE NOT NULL,
  `fechaLlegada` DATE NOT NULL,
  `horaSalida` VARCHAR(45) NOT NULL,
  `horaLlegada` VARCHAR(45) NOT NULL,
  `idVuelo` INT NOT NULL,
  PRIMARY KEY (`idruta`),
  INDEX `fk_ruta_vuelo_id_idx` (`idVuelo` ASC) VISIBLE,
  CONSTRAINT `fk_ruta_vuelo_id`
    FOREIGN KEY (`idVuelo`)
    REFERENCES `vuelos_semillero`.`vuelo` (`idvuelo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vuelos_semillero`.`tripulante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos_semillero`.`tripulante` (
  `idtripulante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtripulante`))
ENGINE = InnoDB
AUTO_INCREMENT = 189365395
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vuelos_semillero`.`vuelo-tripulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos_semillero`.`vuelo-tripulacion` (
  `idvuelo-tripulacion` INT NOT NULL AUTO_INCREMENT,
  `idTripulacion` INT NOT NULL,
  `idVuelo` INT NOT NULL,
  PRIMARY KEY (`idvuelo-tripulacion`),
  INDEX `fk_vuelo-tripulante_vuelo_id_idx` (`idVuelo` ASC) VISIBLE,
  INDEX `fk_vuelo-tripulante_tripulante_id_idx` (`idTripulacion` ASC) VISIBLE,
  CONSTRAINT `fk_vuelo-tripulante_tripulante_id`
    FOREIGN KEY (`idTripulacion`)
    REFERENCES `vuelos_semillero`.`tripulante` (`idtripulante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_vuelo-tripulante_vuelo_id`
    FOREIGN KEY (`idVuelo`)
    REFERENCES `vuelos_semillero`.`vuelo` (`idvuelo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
